---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: arn-wayblue-river
# description will be included in the image's metadata
description: This is the personal OS image of Ashiqur Rahman Niloy (ashiq.r.niloy@gmail.com)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/river
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
#  - type: files
#    files:
#      - source: system
#        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    snippets:
      - FEDORA_VERSION=$(rpm -E %fedora) # get current Fedora version
      - curl -o /etc/yum.repos.d/_copr:alternateved:keyd.repo https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-"$FEDORA_VERSION"/alternateved-keyd-fedora-"$FEDORA_VERSION".repo
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-41/atim-starship-fedora-41.repo
    install:
      - starship
      - docker-compose
      - podman-compose
      - keyd
      - helix
      - swaybg
      - xlsclients
      - syncthing
      - sddm-breeze
      - mako
      - flameshot
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - dunst

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: files
    files:
      - source: system/etc
      - destination: /etc
# chezmoi
# systemd service for emacs

#  - type: default-flatpaks
#    notify: true # Send notification after install/uninstall is finished (true/false)
#    system:
#      # If no repo information is specified, Flathub will be used by default
#      install:
#        - org.mozilla.firefox
#        - org.gnome.Loupe
#      remove:
#        - org.gnome.eog
#    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

